### ISSUE TITLE
TypeError: Cannot find function getNumChildren in object UnsupportedElement.

### ISSUE THREAD

**Issue by Contentwriter87** [seriema/gdocs2md-addon#11]
Hi I am trying to convert documents from word in to markdown and keep getting the above error.

**Comment by seriema** [comment]
> Before you submit an issue, please review the [guidelines for contributing](https://github.com/seriema/gdocs2md-addon/blob/master/CONTRIBUTING.md) to this repository.

It sounds like your issue concerns the actual Markdown so please file it upstream on [gdocs2md](https://github.com/mangini/gdocs2md). This repository is just for the Google Docs addon itself.
