### ISSUE TITLE
Error exporting if empty images exist

### ISSUE THREAD

**Issue by jwerre** [seriema/gdocs2md-addon#13]
I kept getting an error trying to run the plug-in and found it was because I and a bunch of empty image references in my document. I couldn't see them in the document itself but when I exported the document to HTML saw a few empty image tags `<img>`. I was able to find out where they were in the html, then select and delete them in the document (see screenshot). 

<img width="231" alt="screen shot 2017-11-27 at 1 13 03 pm" src="https://user-images.githubusercontent.com/747587/33294463-c787855e-d374-11e7-8440-a2efe2026fd9.png">

**Comment by seriema** [comment]
Thank you for taking the time to report this issue. This repository is just for the Google Docs addon itself and I don't control the upstream repo where the actual conversion script lives. It sounds like your issue concerns the actual Markdown so please file it upstream on [gdocs2md](https://github.com/mangini/gdocs2md).
