### ISSUE TITLE
Image export in gdocs2md

### ISSUE THREAD

**Issue by jimstigler** [seriema/gdocs2md-addon#14]
It would be great if images resized in Google Docs could keep their new size when exported to markdown. This is what happens when I download as a Word file - I don't have to resize the images again. Is it possible to add this feature? I think it should be the default. Thanks.

**Comment by seriema** [comment]
Thank you for taking the time to report this issue. This repository is just for the Google Docs addon itself and I don't control the upstream repo where the actual conversion script lives. It sounds like your issue concerns the actual Markdown so please file it upstream on [gdocs2md](https://github.com/mangini/gdocs2md).
