### ISSUE TITLE
Why do you need ``Allow this application to run when you are not present``?

### ISSUE THREAD

**Issue by jbkoh** [seriema/gdocs2md-addon#15]
If your issue concerns the actual Markdown then please file it upstream on [gdocs2md](https://github.com/mangini/gdocs2md).

Hi,

I like the idea of your app very much, but for now, I'm hesitating to install it due to its permission level. Could you clarify why you need ``Allow this application to run when you are not present``?

Thanks!

**Comment by seriema** [comment]
Don’t know. But it doesn’t matter anymore because it’s delisted now.
