### ISSUE TITLE
Support for &

### ISSUE THREAD

**Issue by justin808** [seriema/gdocs2md-addon#4]
Thanks for working on this!

I just tried this, and there's one big show stopper is the handling the the `&`.

We need to convert this to `&amp;`

And this probably applies to `<` which needs to be `&lt;`

Reference: https://daringfireball.net/projects/markdown/syntax

**Comment by seriema** [comment]
Thank you for using it!

The conversion is actually done by the [gdocs2md script](https://github.com/mangini/gdocs2md) which I don't control.

If there's enough interest I'll fork that project and start fixing these issues myself or with the help of PR's. For now, I'll close all issues about it.
