### ISSUE TITLE
problem with bold word with comma afterwards

### ISSUE THREAD

**Issue by justin808** [seriema/gdocs2md-addon#5]
This is the google doc:

![2016-07-09_09-27-25](https://cloud.githubusercontent.com/assets/1118459/16709819/66907824-45b7-11e6-9f79-73dbfb729fce.png)

This is the generated markdown:

```
If you’re a **guest, **the best way to join Friends and Guests is to "**Get on the Guest List!**". Any host can invite you. You can also sign up right now, and you’ll be alerted once we start general enrollment, and if a host does invite you, you’ll immediately be notified and have access.
```

And this is how it looks on github:

![2016-07-09_09-28-48](https://cloud.githubusercontent.com/assets/1118459/16709820/91313ce4-45b7-11e6-951e-bf3fb55dffd9.png)

**Comment by seriema** [comment]
Thank you for putting time into reporting this.

The conversion is actually done by the [gdocs2md script](https://github.com/mangini/gdocs2md) which I don't control.

If there's enough interest I'll fork that project and start fixing these issues myself or with the help of PR's. For now, I'll close all issues about it.
