### ISSUE TITLE
Cannot nest bullets under numbers

### ISSUE THREAD

**Issue by justin808** [seriema/gdocs2md-addon#6]
This is the gdoc:
![2016-07-09_09-52-23](https://cloud.githubusercontent.com/assets/1118459/16709954/e68f2608-45ba-11e6-9c68-3396c15f51ea.png)

This is the generated markdown. The nest numbers should be stars.

```
3. Your "Friends &amp; Contacts" can see just:

    1. Title of the listing

    2. Your name as the host

    3. Approximate location within a mile

    4. A "Welcome Message" where you can put any text you like to tell your “Friends and Contacts” just a little or a lot about your listing.
```

However, if the bullets are on the last number, the bullets come out OK.

**Comment by seriema** [comment]
Thank you for putting time into reporting this.

The conversion is actually done by the [gdocs2md script](https://github.com/mangini/gdocs2md) which I don't control.

If there's enough interest I'll fork that project and start fixing these issues myself or with the help of PR's. For now, I'll close all issues about it.
