### ISSUE TITLE
Paragraph 23 of type PARAGRAPH has an unsupported child: INLINE_DRAWING index=23 (line 155, file "Code")

### ISSUE THREAD

**Issue by JOY** [seriema/gdocs2md-addon#7]
I have this error while running the script:

Paragraph 23 of type PARAGRAPH has an unsupported child: INLINE_DRAWING index=23 (line 155, file "Code")

This line: "throw "Paragraph "+index+" of type "+element.getType()+" has an unsupported child: ""

**Comment by seriema** [comment]
Seems like there's an inline drawing in your document? The conversion is actually done by the [gdocs2md script](https://github.com/mangini/gdocs2md) which I don't control.

**Comment by seriema** [comment]
I see you logged an issue there so I'm closing this.
https://github.com/mangini/gdocs2md/issues/45
