### ISSUE TITLE
Allow configuration of space after bullet or numbered list items

### ISSUE THREAD

**Issue by frafor** [seriema/gdocs2md-addon#9]
Some of us prefer our bullet and number lists without extra space between items.

Instead of this:

1. Item 1

2. Item 2

Some of us prefer this:

1. Item 1
2. Item 2

Without the *extra* space between items.

Google docs do not add extra space after bullet or numbered lists.

**Comment by seriema** [comment]
Thank you for your comment. Any issues about the generated markdown is outside my control, so please log it upstream on https://github.com/mangini/gdocs2md/issues.
